@startuml
interface com.example.spring_security_cifrado.UserRepository {
}
class com.example.spring_security_cifrado.User {
- Long id
- String username
- String password
+ <<Create>> User()
+ <<Create>> User(Long,String,String)
+ Long getId()
+ void setId(Long)
+ String getUsername()
+ void setUsername(String)
+ String getPassword()
+ void setPassword(String)
}


class com.example.spring_security_cifrado.SecurityConfig {
+ PasswordEncoder passwordEncoder()
}

class com.example.spring_security_cifrado.SpringSecurityCifradoApplication {
+ {static} void main(String[])
}



org.springframework.data.jpa.repository.JpaRepository <|-- com.example.spring_security_cifrado.UserRepository
@enduml